name: Create Spoke Issue

on:
  workflow_dispatch:
    inputs:
      hub_name:
        description: "Hub Name (e.g., hub_weu, hub_neu)"
        required: true
        type: choice
        options:
          - hub_weu
          - hub_neu
          - hub_weu_stg
          - hub_eastus

      spoke_name:
        description: "Spoke Name (e.g., hau_ops_private_aks)"
        required: true
        type: string

      subscription_id:
        description: "Azure Subscription ID (UUID format)"
        required: true
        type: string

      size:
        description: "VNET Size"
        required: true
        type: choice
        options:
          - 16
          - 32
          - 64
          - 128
          - 256
          - 512

      description:
        description: "Short description of the spoke"
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create Spoke Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        HUB_NAME: ${{ github.event.inputs.hub_name }}
        SPOKE_NAME: ${{ github.event.inputs.spoke_name }}
        SUBSCRIPTION_ID: ${{ github.event.inputs.subscription_id }}
        SIZE: ${{ github.event.inputs.size }}
        SPOKE_DESCRIPTION: ${{ github.event.inputs.description }}
      run: |
        ISSUE_TITLE="[${SPOKE_NAME}]: Add Spoke"
        
        ISSUE_BODY="## Spoke Creation Request

**Hub Name:** ${HUB_NAME}  
**Spoke Name:** ${SPOKE_NAME}  
**Subscription ID:** ${SUBSCRIPTION_ID}  
**Size:** ${SIZE}  
**Description:** ${SPOKE_DESCRIPTION}

---

_This issue was automatically generated by a GitHub Action workflow._"

        curl -s -X POST https://api.github.com/repos/$REPO/issues \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          -d @- <<EOF
        {
          "title": "${ISSUE_TITLE}",
          "body": "${ISSUE_BODY}",
          "labels": ["add spoke"]
        }
EOF
