name: Create Spoke Issue

on:
  workflow_dispatch:
    inputs:
      buildingBlockRun:
        description: "meshStack Building Block Run (Base64 encoded)"
        required: true

jobs:
  create-issue:
    runs-on: visa

    steps:
    - name: Create Spoke Issue
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        REPO: ${{ github.repository }}
        BUILDING_BLOCK_RUN: ${{ github.event.inputs.buildingBlockRun }}
      
      run: |
        # Decode base64 input
        echo "$BUILDING_BLOCK_RUN" | base64 --decode > run.json

        # Extract variables using jq
        HUB_NAME=$(jq -r '.spec.buildingBlock.spec.inputs[] | select(.key=="hub_name") | .value' run.json)
        SPOKE_NAME=$(jq -r '.spec.buildingBlock.spec.inputs[] | select(.key=="spoke_name") | .value' run.json)
        SUBSCRIPTION_ID=$(jq -r '.spec.buildingBlock.spec.inputs[] | select(.key=="subscription_id") | .value' run.json)
        SIZE=$(jq -r '.spec.buildingBlock.spec.inputs[] | select(.key=="size") | .value' run.json)
        SPOKE_DESCRIPTION=$(jq -r '.spec.buildingBlock.spec.inputs[] | select(.key=="description") | .value' run.json)

        ISSUE_TITLE="[${SPOKE_NAME}]: Add new spoke"

        ISSUE_BODY=$(cat <<EOF
        Hello,
        
        this template will create a new spoke. Fill out the required information below; we will
        automatically generate a pull request for you.
        
        Thanks!
        
        **Hub Name:** ${HUB_NAME}  
        **Spoke Name:** ${SPOKE_NAME}  
        **Subscription ID:** ${SUBSCRIPTION_ID}  
        **Size:** ${SIZE}  
        **Description:** ${SPOKE_DESCRIPTION}
        EOF
                )

        curl -s -X POST https://api.github.com/repos/${REPO}/issues \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github+json" \
          -d "$(jq -n \
            --arg title "$ISSUE_TITLE" \
            --arg body "$ISSUE_BODY" \
            --argjson labels '["add spoke"]' \
            '{title: $title, body: $body, labels: $labels}')"
